[package]
name = "mindboggling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
packed_simd = "0.3.8"
pretty_env_logger = "0.4.0"
